Read in art products for wire-cell imaging
LArSoft/larwirecell pull request #36
Opened 2023-08-31 12:23 UTC by ebelchio12

2023-08-31 12:23 UTC, FNALbuild commented
A new Pull Request was created by  @ebelchio12 (Ewerton Belchior) for develop.

It involves the following packages:

larwirecell


@LArSoft/level-1-managers, @LArSoft/level-2-managers can you please review it and eventually sign? Thanks.

cms-bot commands are listed <a href="https://cdcvs.fnal.gov/redmine/projects/larsoft/wiki/Pull_request_comments_that_trigger_CI_actions">here</a>

2023-08-31 12:23 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2023-08-31 12:24 UTC, FNALbuild commented
-code-checks
Pull request failed code-formatting checks. Please ensure that `cetmodules` has been setup and execute the following command from the top-level directory of your repository:

```
format-code \
  larwirecell/Components/CookedFrameSource.cxx
```
Then commit the changes and push them to your PR branch.

2023-08-31 15:26 UTC, lgarren commented
@ebelchio12  Please apply the clang format as mentioned here: https://github.com/LArSoft/larwirecell/pull/36#issuecomment-1700937799

2023-08-31 19:00 UTC, brettviren commented
Hi @ebelchio12 

Notes from our meeting

- [ ] remove the `imaging` configuration and instead simply don't apply the new CMM making if the user supplies none of the other new configuration that describes how the CMM is to be built.
- [ ] consider making a unit test from your validation job and getting it integrated into LArSoft CI.  The test can be as simple as using `grep` and `awk` to get at the log lines that you are already checking manually and doing a `diff`.  If the `diff` fails, then the test fails.

2023-09-06 16:28 UTC, FNALbuild commented
Pull request #36 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2023-09-06 16:28 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2023-09-06 16:29 UTC, FNALbuild commented
+code-checks

2023-09-06 17:30 UTC, brettviren requested changes

2023-09-06 17:30 UTC, brettviren commented on larwirecell/Components/CookedFrameSource.cxx
> +  cfg["gauss_inputTag"] = "";                  // art tag for gauss recob::Wire
I'll just make one big comment but it applies to essentially this whole diff.

There are two main problems with this PR that must be cleaned up.   They are like we discussed on zoom and I commented on in the PR.

1. This class must work for a wide variety of users and so should not have any application specific information that is hard-wired in C++ or in configuration.  Ie, there should be no configuration keys nor C++ symbols that include the label `wiener` or `bad`, etc.  Instead, the C++ should be purely "data driven" by the configuration.

2. There should be no "modal" `true/false` configuration values.  Instead, if some action is to be taken by the class then the configuration values needed to perform that action will be given.  If no such configuration values are given then the class simply does not take the action.


Specifically:

- Remove all the `*_inputTag` configuration and code that touches them.  There is already a `frame_tags` configuration and that is generic and is interpreted by converting `art::Event` data into frame traces.

- Remove the current `cmm_tag` (and `badmasks_inputTag`) configuration and all code that touches them.  What the user must supply is a instead mapping that associates a CMM **key** (eg `"bad"` to an `art::Event` **label**.  I would call this configuration parameter, perhaps, `cmm_entries`.

- Remove `m_cmm_setup` and instead convert CMM information (using your existing  by iterating on the new `cmm_entries` configuration.  If that configuration is empty then so is the loop body.  The actual conversion code you have at the end of this diff (the loop over `bad_masks`, but again, the symbol "bad" is ... bad) looks okay to me.

2023-09-06 17:30 UTC, brettviren commented on larwirecell/Components/CookedFrameSource.cxx
> +    cmm[m_cmm_tag] = cm_out; // for now use a single tag for output cmm
I think this is mostly okay but do not use the symbol `bad` and save into the `cmm` using the **key** from the `cmm_entries` configuration and not any singular name (ie, remove `m_cmm_tag` entirely).

2023-09-18 15:34 UTC, knoepfel commented
@ebelchio12, is there any update on this?

2025-01-06 21:34 UTC, HaiwangYu commented
@knoepfel this can be closed now, the content of this PR is included in #49

2025-01-06 21:46 UTC, closed without merging